language: scala

jdk: openjdk11

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-scripts
env:
  global:
    - PGPORT=5433

services:
  postgresql

before_script:
  - psql -c 'create database mr_test;' -U postgres
  - psql -c 'CREATE USER osm WITH PASSWORD 'osm';" -U postgres

script:
  - sbt clean scalafmtCheckAll compile test

