name: Scala CI

on:
  push:
    # branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgis11:
        image: postgis/postgis:11-2.5
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: mr_test
          POSTGRES_USER: osm
          POSTGRES_PASSWORD: osm

    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: 'osmlab/maproulette-java-client'
        path: 'java-client'
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Run sbt compile
      run: sbt compile
    - run: 'ls'
    - name: Create the dev.conf
      run: |
        cat > ./conf/dev.conf << EOF 
        include "application.conf"
        db.default {
          url="jdbc:postgresql://localhost:5432/mr_test"
          username="osm"
          password="osm"
        }
        maproulette {
          debug=true
          bootstrap=true
          super.key="1234"
          super.accounts=""
        }
        EOF
    - name: Run the integration tests
      env:
        SBT_OPTS: "-Xms512M -Xmx1024M -Xss2M -XX:MaxMetaspaceSize=1024M"
        API_HOST: 127.0.0.1:9000
        host: 127.0.0.1
        scheme: http
        apiKey: 1234
      run: |
          sbt -Dconfig.file=./conf/dev.conf run &
        sleep 10
        cd java-client
          host=127.0.0.1 scheme=http apiKey=1234
          ./gradlew --info --project-prop runIntegrationTests
            clean integrationTest
            --tests '*BatchUploaderIntegrationTest*'
            --tests '*ChallengeAPIIntegrationTest*'

